name: chestxray
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - ca-certificates=2022.07.19=h06a4308_0
  - certifi=2022.9.14=py37h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - ncurses=6.3=h5eee18b_3
  - openssl=1.1.1q=h7f8727e_0
  - pip=22.1.2=py37h06a4308_0
  - python=3.7.13=h12debd9_0
  - readline=8.1.2=h7f8727e_1
  - setuptools=63.4.1=py37h06a4308_0
  - sqlite=3.39.2=h5082296_0
  - tk=8.6.12=h1ccaba5_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.5=h7f8727e_1
  - zlib=1.2.12=h5eee18b_3
  - pip:
    - albumentations==1.3.0
    - altair==4.2.0
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - attrs==22.1.0
    - backcall==0.2.0
    - beautifulsoup4==4.11.1
    - bleach==5.0.1
    - catalogue==2.0.8
    - cffi==1.15.1
    - charset-normalizer==2.1.1
    - click==8.1.3
    - commonmark==0.9.1
    - cycler==0.11.0
    - debugpy==1.6.3
    - decorator==5.1.1
    - defusedxml==0.7.1
    - dill==0.3.5.1
    - docker-pycreds==0.4.0
    - entrypoints==0.4
    - fastcore==1.5.27
    - fastjsonschema==2.16.2
    - fonttools==4.37.3
    - fuzzywuzzy==0.18.0
    - gitdb==4.0.9
    - gitpython==3.1.27
    - glob2==0.7
    - idna==3.4
    - imageio==2.22.0
    - imgaug==0.4.0
    - importlib-metadata==4.12.0
    - importlib-resources==5.9.0
    - ipykernel==6.15.3
    - ipython==7.34.0
    - ipython-genutils==0.2.0
    - ipywidgets==8.0.2
    - jedi==0.18.1
    - jinja2==3.1.2
    - joblib==1.2.0
    - jsonlines==3.1.0
    - jsonschema==4.16.0
    - jupyter==1.0.0
    - jupyter-client==7.3.5
    - jupyter-console==6.4.4
    - jupyter-core==4.11.1
    - jupyterlab-pygments==0.2.2
    - jupyterlab-widgets==3.0.3
    - kiwisolver==1.4.4
    - loguru==0.6.0
    - lxml==4.9.1
    - markupsafe==2.1.1
    - matplotlib==3.5.3
    - matplotlib-inline==0.1.6
    - mistune==2.0.4
    - nbclient==0.6.8
    - nbconvert==7.0.0
    - nbformat==5.6.0
    - nest-asyncio==1.5.5
    - networkx==2.6.3
    - nltk==3.7
    - notebook==6.4.12
    - numpy==1.21.6
    - opencv-python==4.6.0.66
    - opencv-python-headless==4.6.0.66
    - packaging==21.3
    - pandas==1.3.5
    - pandocfilters==1.5.0
    - parso==0.8.3
    - pathtools==0.1.2
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==9.2.0
    - pkgutil-resolve-name==1.3.10
    - prometheus-client==0.14.1
    - promise==2.3
    - prompt-toolkit==3.0.31
    - protobuf==3.20.2
    - psutil==5.9.2
    - ptyprocess==0.7.0
    - pycparser==2.21
    - pydantic==1.10.2
    - pydicom==2.3.0
    - pygments==2.13.0
    - pyparsing==3.0.9
    - pyrsistent==0.18.1
    - python-dateutil==2.8.2
    - python-levenshtein==0.12.2
    - pytz==2022.2.1
    - pywavelets==1.3.0
    - pyyaml==6.0
    - pyzmq==24.0.1
    - qtconsole==5.3.2
    - qtpy==2.2.0
    - qudida==0.0.4
    - regex==2022.9.13
    - requests==2.28.1
    - rich==12.5.1
    - scikit-image==0.19.3
    - scikit-learn==1.0.2
    - scipy==1.7.3
    - send2trash==1.8.0
    - sentry-sdk==1.9.8
    - setproctitle==1.3.2
    - shapely==1.8.4
    - shortuuid==1.0.9
    - six==1.16.0
    - sklearn==0.0
    - smmap==5.0.0
    - soupsieve==2.3.2.post1
    - srsly==2.4.4
    - terminado==0.15.0
    - threadpoolctl==3.1.0
    - tifffile==2021.11.2
    - tinycss2==1.1.1
    - toolz==0.12.0
    - torch==1.12.1
    - torch-snippets==0.499.4
    - torchaudio==0.12.1
    - torchvision==0.13.1
    - tornado==6.2
    - tqdm==4.64.1
    - traitlets==5.4.0
    - typing==3.7.4.3
    - typing-extensions==4.3.0
    - urllib3==1.26.12
    - wandb==0.13.3
    - wasabi==0.10.1
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - widgetsnbextension==4.0.3
    - xmltodict==0.13.0
    - zipp==3.8.1
prefix: /root/anaconda3/envs/chestxray
